[project]
name = "cs2-tactical-intelligence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhenchenglin", email = "zhl132@ucsd.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "awpy>=2.0.2",
    "curl-cffi>=0.16.3",
    "scikit-learn>=1.9.0",
    "xgboost>=3.4.1",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
